"""Create a synthetic CC0 example pack containing an original 16px raster smile."""

import argparse
import hashlib
import json
import struct
import zlib
import zipfile
from pathlib import Path


def chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    rows = b""
    for y in range(16):
        rows += b"\0"
        for x in range(16):
            ink = (
                (x in (5, 10) and y == 5) or (y == 10 and 5 <= x <= 10) or (y == 9 and x in (4, 11))
            )
            rows += bytes((35, 35, 35, 255) if ink else (255, 210, 60, 255))
    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", 16, 16, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(rows))
        + chunk(b"IEND", b"")
    )
    manifest = {
        "schema": 1,
        "id": "synthetic-smile",
        "version": "1.0.0",
        "name": "Synthetic smile",
        "source": "Original procedural raster generated by example_emoji_pack.py",
        "license": "CC0-1.0",
        "emoji": {"smile": {"file": "smile.png", "sha256": hashlib.sha256(png).hexdigest()}},
    }
    with zipfile.ZipFile(args.output, "x", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("manifest.json", json.dumps(manifest))
        archive.writestr("smile.png", png)
    print(args.output)


if __name__ == "__main__":
    main()
